defer searching $PATH for vcexe until later; better errors
Before this change, a missing vcexe would cause something like

    exceptions.RuntimeError: Couldn't find executable for 'hg'

With this change, a missing vcexe gives something like

    could not find 'hg'
    PATH is 'blah blah blah'
    program finished with exit code -1

Fixes #783